'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
'
Namespace IMaestroMasterDataManager
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="MasterDataManagerPortBinding", [Namespace]:="http://soa.weg.net/eng/maestro/masterDataManager")>  _
    Partial Public Class MasterDataManagerService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private userField As [string]
        
        Private mergeValueDescriptionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private mergeCharacteristicDescriptionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.MaestroMasterDataImporter.My.MySettings.Default.MaestroMasterDataImporter_IMaestroMasterDataManager_MasterDataManagerService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property User() As [string]
            Get
                Return Me.userField
            End Get
            Set
                Me.userField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event mergeValueDescriptionCompleted As mergeValueDescriptionCompletedEventHandler
        
        '''<remarks/>
        Public Event mergeCharacteristicDescriptionCompleted As mergeCharacteristicDescriptionCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("User"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function mergeValueDescription(<System.Xml.Serialization.XmlElementAttribute("mergeValueDescription", [Namespace]:="http://soa.weg.net/eng/maestro/masterDataManager")> ByVal mergeValueDescription1 As mergeValueDescription) As <System.Xml.Serialization.XmlElementAttribute("mergeValueDescriptionResponse", [Namespace]:="http://soa.weg.net/eng/maestro/masterDataManager")> mergeValueDescriptionResponse
            Dim results() As Object = Me.Invoke("mergeValueDescription", New Object() {mergeValueDescription1})
            Return CType(results(0),mergeValueDescriptionResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub mergeValueDescriptionAsync(ByVal mergeValueDescription1 As mergeValueDescription)
            Me.mergeValueDescriptionAsync(mergeValueDescription1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub mergeValueDescriptionAsync(ByVal mergeValueDescription1 As mergeValueDescription, ByVal userState As Object)
            If (Me.mergeValueDescriptionOperationCompleted Is Nothing) Then
                Me.mergeValueDescriptionOperationCompleted = AddressOf Me.OnmergeValueDescriptionOperationCompleted
            End If
            Me.InvokeAsync("mergeValueDescription", New Object() {mergeValueDescription1}, Me.mergeValueDescriptionOperationCompleted, userState)
        End Sub
        
        Private Sub OnmergeValueDescriptionOperationCompleted(ByVal arg As Object)
            If (Not (Me.mergeValueDescriptionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent mergeValueDescriptionCompleted(Me, New mergeValueDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("User"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function mergeCharacteristicDescription(<System.Xml.Serialization.XmlElementAttribute("mergeCharacteristicDescription", [Namespace]:="http://soa.weg.net/eng/maestro/masterDataManager")> ByVal mergeCharacteristicDescription1 As mergeCharacteristicDescription) As <System.Xml.Serialization.XmlElementAttribute("mergeCharacteristicDescriptionResponse", [Namespace]:="http://soa.weg.net/eng/maestro/masterDataManager")> mergeCharacteristicDescriptionResponse
            Dim results() As Object = Me.Invoke("mergeCharacteristicDescription", New Object() {mergeCharacteristicDescription1})
            Return CType(results(0),mergeCharacteristicDescriptionResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub mergeCharacteristicDescriptionAsync(ByVal mergeCharacteristicDescription1 As mergeCharacteristicDescription)
            Me.mergeCharacteristicDescriptionAsync(mergeCharacteristicDescription1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub mergeCharacteristicDescriptionAsync(ByVal mergeCharacteristicDescription1 As mergeCharacteristicDescription, ByVal userState As Object)
            If (Me.mergeCharacteristicDescriptionOperationCompleted Is Nothing) Then
                Me.mergeCharacteristicDescriptionOperationCompleted = AddressOf Me.OnmergeCharacteristicDescriptionOperationCompleted
            End If
            Me.InvokeAsync("mergeCharacteristicDescription", New Object() {mergeCharacteristicDescription1}, Me.mergeCharacteristicDescriptionOperationCompleted, userState)
        End Sub
        
        Private Sub OnmergeCharacteristicDescriptionOperationCompleted(ByVal arg As Object)
            If (Not (Me.mergeCharacteristicDescriptionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent mergeCharacteristicDescriptionCompleted(Me, New mergeCharacteristicDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2001/XMLSchema"),  _
     System.Xml.Serialization.XmlRootAttribute("User", [Namespace]:="http://soa.weg.net/eng/maestro/masterDataManager", IsNullable:=true)>  _
    Partial Public Class [string]
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private textField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soa.weg.net/eng/maestro/masterDataManager")>  _
    Partial Public Class mergeValueDescription
        
        Private languageField As String
        
        Private characteristicNameField As String
        
        Private characteristicValueField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property language() As String
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property characteristicName() As String
            Get
                Return Me.characteristicNameField
            End Get
            Set
                Me.characteristicNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property characteristicValue() As String
            Get
                Return Me.characteristicValueField
            End Get
            Set
                Me.characteristicValueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soa.weg.net/eng/maestro/masterDataManager")>  _
    Partial Public Class mergeCharacteristicDescriptionResponse
        
        Private masterDataManagerField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MasterDataManager() As Boolean
            Get
                Return Me.masterDataManagerField
            End Get
            Set
                Me.masterDataManagerField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soa.weg.net/eng/maestro/masterDataManager")>  _
    Partial Public Class mergeCharacteristicDescription
        
        Private languageField As String
        
        Private characteristicNameField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property language() As String
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property characteristicName() As String
            Get
                Return Me.characteristicNameField
            End Get
            Set
                Me.characteristicNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://soa.weg.net/eng/maestro/masterDataManager")>  _
    Partial Public Class mergeValueDescriptionResponse
        
        Private masterDataManagerField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MasterDataManager() As Boolean
            Get
                Return Me.masterDataManagerField
            End Get
            Set
                Me.masterDataManagerField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub mergeValueDescriptionCompletedEventHandler(ByVal sender As Object, ByVal e As mergeValueDescriptionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class mergeValueDescriptionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As mergeValueDescriptionResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),mergeValueDescriptionResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub mergeCharacteristicDescriptionCompletedEventHandler(ByVal sender As Object, ByVal e As mergeCharacteristicDescriptionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class mergeCharacteristicDescriptionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As mergeCharacteristicDescriptionResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),mergeCharacteristicDescriptionResponse)
            End Get
        End Property
    End Class
End Namespace
